namespace Assignment.Api.Responses;

public record FindManyClassificationsResponse
{
    public int? YearId { get; set; }
    public int? TeacherId { get; set; }
    public int? SubscriptionId { get; set; }
    public string? Name { get; set; }
    public int? SituationId { get; set; }
    public string? Situation { get; set; }
    public int? PositionId { get; set; }
    public string? Position { get; set; }
    public int? UnitId { get; set; }
    public string? Unit { get; set; }
    public int? DisciplineId { get; set; }
    public string? Discipline { get; set; }
    public string? Phone { get; set; }
    public string? Cellphone { get; set; }
    public string? Speciality { get; set; }
    public string? Remove { get; set; }
    public string? Adido { get; set; }
    public string? Readapted { get; set; }
    public string? ReadingRoom { get; set; }
    public string? Computing { get; set; }
    public string? SupplementCharge { get; set; }
    public string? Tutoring { get; set; }
    public string? AmbientalEducation { get; set; }
    public decimal? T1 { get; set; }
    public decimal? T2 { get; set; }
    public decimal? T3 { get; set; }
    public decimal? T4 { get; set; }
    public decimal? T5 { get; set; }
    public decimal? T6 { get; set; }
    public decimal? T7 { get; set; }
    public decimal? T8 { get; set; }
    public decimal? T9 { get; set; }
    public decimal? T10 { get; set; }
    public decimal? T11 { get; set; }
    public decimal? T12 { get; set; }
    public decimal? T13 { get; set; }
    public decimal? T14 { get; set; }
    public decimal? T15 { get; set; }
    public decimal? T16 { get; set; }
    public decimal? T17 { get; set; }
    public decimal? T18 { get; set; }
    public decimal? T19 { get; set; }
    public decimal? T20 { get; set; }
    public decimal? T21 { get; set; }
    public decimal? T22 { get; set; }
    public decimal? Total { get; set; }
}

public record FindOneClassificationsResponse
{
    public int? YearId { get; set; }
    public int? TeacherId { get; set; }
    public int? SubscriptionId { get; set; }
    public string? Name { get; set; }
    public int? SituationId { get; set; }
    public string? Situation { get; set; }
    public int? PositionId { get; set; }
    public string? Position { get; set; }
    public int? UnitId { get; set; }
    public string? Unit { get; set; }
    public int? DisciplineId { get; set; }
    public string? Discipline { get; set; }
    public string? Phone { get; set; }
    public string? Cellphone { get; set; }
    public string? Speciality { get; set; }
    public string? Remove { get; set; }
    public string? Adido { get; set; }
    public string? Readapted { get; set; }
    public string? ReadingRoom { get; set; }
    public string? Computing { get; set; }
    public string? SupplementCharge { get; set; }
    public string? Tutoring { get; set; }
    public string? AmbientalEdication { get; set; }
    public decimal? T1 { get; set; }
    public decimal? T2 { get; set; }
    public decimal? T3 { get; set; }
    public decimal? T4 { get; set; }
    public decimal? T5 { get; set; }
    public decimal? T6 { get; set; }
    public decimal? T7 { get; set; }
    public decimal? T8 { get; set; }
    public decimal? T9 { get; set; }
    public decimal? T10 { get; set; }
    public decimal? T11 { get; set; }
    public decimal? T12 { get; set; }
    public decimal? T13 { get; set; }
    public decimal? T14 { get; set; }
    public decimal? T15 { get; set; }
    public decimal? T16 { get; set; }
    public decimal? T17 { get; set; }
    public decimal? T18 { get; set; }
    public decimal? T19 { get; set; }
    public decimal? T20 { get; set; }
    public decimal? T21 { get; set; }
    public decimal? T22 { get; set; }
    public decimal? Total { get; set; }
}
