//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Api.Resources.Messages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Assignment.Api.Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        public static string PositiveValue {
            get {
                return ResourceManager.GetString("PositiveValue", resourceCulture);
            }
        }
        
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        public static string invalidTime {
            get {
                return ResourceManager.GetString("invalidTime", resourceCulture);
            }
        }
        
        public static string DateGreatherThanCurrent {
            get {
                return ResourceManager.GetString("DateGreatherThanCurrent", resourceCulture);
            }
        }
        
        public static string DateGreatherThan {
            get {
                return ResourceManager.GetString("DateGreatherThan", resourceCulture);
            }
        }
        
        public static string TimeGreatherThanCurrent {
            get {
                return ResourceManager.GetString("TimeGreatherThanCurrent", resourceCulture);
            }
        }
        
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        public static string InvalidBoolean {
            get {
                return ResourceManager.GetString("InvalidBoolean", resourceCulture);
            }
        }
        
        public static string DatePresentPast {
            get {
                return ResourceManager.GetString("DatePresentPast", resourceCulture);
            }
        }
        
        public static string Parser_ToGuid_Invalid_GUID_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToGuid_Invalid_GUID_format___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToEnum_Invalid_ENUM_value___0_ {
            get {
                return ResourceManager.GetString("Parser_ToEnum_Invalid_ENUM_value___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToDateOnly_Invalid_DateOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToDateOnly_Invalid_DateOnly_format___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToTimeOnly_Invalid_TimeOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToTimeOnly_Invalid_TimeOnly_format___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToBool_Invalid_boolean_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToBool_Invalid_boolean_format___0_", resourceCulture);
            }
        }
        
        public static string ConnectionNotFound {
            get {
                return ResourceManager.GetString("ConnectionNotFound", resourceCulture);
            }
        }
        
        public static string MustBeAOneOfTheseValues {
            get {
                return ResourceManager.GetString("MustBeAOneOfTheseValues", resourceCulture);
            }
        }
        
        public static string UserConnectionNotFound {
            get {
                return ResourceManager.GetString("UserConnectionNotFound", resourceCulture);
            }
        }
        
        public static string UsersRepositoryNotAvailable {
            get {
                return ResourceManager.GetString("UsersRepositoryNotAvailable", resourceCulture);
            }
        }
        
        public static string TimePresentPast {
            get {
                return ResourceManager.GetString("TimePresentPast", resourceCulture);
            }
        }
        
        public static string UniqueField {
            get {
                return ResourceManager.GetString("UniqueField", resourceCulture);
            }
        }
        
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        public static string DontRemoveYourself {
            get {
                return ResourceManager.GetString("DontRemoveYourself", resourceCulture);
            }
        }
        
        public static string QuantityOverStock {
            get {
                return ResourceManager.GetString("QuantityOverStock", resourceCulture);
            }
        }
        
        public static string AuthInactiveUser {
            get {
                return ResourceManager.GetString("AuthInactiveUser", resourceCulture);
            }
        }
        
        public static string AuthInvalidPassword {
            get {
                return ResourceManager.GetString("AuthInvalidPassword", resourceCulture);
            }
        }
        
        public static string AuthInvalidUsername {
            get {
                return ResourceManager.GetString("AuthInvalidUsername", resourceCulture);
            }
        }
        
        public static string UnitNotFound {
            get {
                return ResourceManager.GetString("UnitNotFound", resourceCulture);
            }
        }
        
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        public static string UserUsernameExists {
            get {
                return ResourceManager.GetString("UserUsernameExists", resourceCulture);
            }
        }
        
        public static string UserLoggedIdRequired {
            get {
                return ResourceManager.GetString("UserLoggedIdRequired", resourceCulture);
            }
        }
        
        public static string UserEmailExists {
            get {
                return ResourceManager.GetString("UserEmailExists", resourceCulture);
            }
        }
        
        public static string UserLoggedIdEquals {
            get {
                return ResourceManager.GetString("UserLoggedIdEquals", resourceCulture);
            }
        }
        
        public static string CivilStatusNotFound {
            get {
                return ResourceManager.GetString("CivilStatusNotFound", resourceCulture);
            }
        }
        
        public static string ClassificationNotFound {
            get {
                return ResourceManager.GetString("ClassificationNotFound", resourceCulture);
            }
        }
        
        public static string DisciplineNotFound {
            get {
                return ResourceManager.GetString("DisciplineNotFound", resourceCulture);
            }
        }
        
        public static string PositionNotFound {
            get {
                return ResourceManager.GetString("PositionNotFound", resourceCulture);
            }
        }
        
        public static string PreferenceNotFound {
            get {
                return ResourceManager.GetString("PreferenceNotFound", resourceCulture);
            }
        }
        
        public static string SituationNotFound {
            get {
                return ResourceManager.GetString("SituationNotFound", resourceCulture);
            }
        }
        
        public static string SubscriptionNotFound {
            get {
                return ResourceManager.GetString("SubscriptionNotFound", resourceCulture);
            }
        }
        
        public static string TeacherNotFound {
            get {
                return ResourceManager.GetString("TeacherNotFound", resourceCulture);
            }
        }
        
        public static string TitleNotFound {
            get {
                return ResourceManager.GetString("TitleNotFound", resourceCulture);
            }
        }
        
        public static string YearNotFound {
            get {
                return ResourceManager.GetString("YearNotFound", resourceCulture);
            }
        }
    }
}
