//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Api.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment.Api.Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inativo.
        /// </summary>
        public static string AuthInactiveUser {
            get {
                return ResourceManager.GetString("AuthInactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha inválida.
        /// </summary>
        public static string AuthInvalidPassword {
            get {
                return ResourceManager.GetString("AuthInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inválido.
        /// </summary>
        public static string AuthInvalidUsername {
            get {
                return ResourceManager.GetString("AuthInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O(A) {0} com o id &apos;{1}&apos; não foi encontrado..
        /// </summary>
        public static string ConnectionNotFound {
            get {
                return ResourceManager.GetString("ConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma data maior que {1}.
        /// </summary>
        public static string DateGreatherThan {
            get {
                return ResourceManager.GetString("DateGreatherThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior que a data atual.
        /// </summary>
        public static string DateGreatherThanCurrent {
            get {
                return ResourceManager.GetString("DateGreatherThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma data menor ou igual a atual.
        /// </summary>
        public static string DatePresentPast {
            get {
                return ResourceManager.GetString("DatePresentPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é permitido o usuário remover a si próprio..
        /// </summary>
        public static string DontRemoveYourself {
            get {
                return ResourceManager.GetString("DontRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um valor booleano válido.
        /// </summary>
        public static string InvalidBoolean {
            get {
                return ResourceManager.GetString("InvalidBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma data válida.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} precisa ser um CPF válido..
        /// </summary>
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um valor UUID válido.
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um horário válido.
        /// </summary>
        public static string invalidTime {
            get {
                return ResourceManager.GetString("invalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve conter até {1} caracteres.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve conter no mínimo {1} caracteres.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um dos seguintes valores: {1}..
        /// </summary>
        public static string MustBeAOneOfTheseValues {
            get {
                return ResourceManager.GetString("MustBeAOneOfTheseValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid boolean format: {0}.
        /// </summary>
        public static string Parser_ToBool_Invalid_boolean_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToBool_Invalid_boolean_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid DateOnly format: {0}.
        /// </summary>
        public static string Parser_ToDateOnly_Invalid_DateOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToDateOnly_Invalid_DateOnly_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid ENUM value: {0}.
        /// </summary>
        public static string Parser_ToEnum_Invalid_ENUM_value___0_ {
            get {
                return ResourceManager.GetString("Parser_ToEnum_Invalid_ENUM_value___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid GUID format: {0}.
        /// </summary>
        public static string Parser_ToGuid_Invalid_GUID_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToGuid_Invalid_GUID_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid TimeOnly format: {0}.
        /// </summary>
        public static string Parser_ToTimeOnly_Invalid_TimeOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToTimeOnly_Invalid_TimeOnly_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um número positivo.
        /// </summary>
        public static string PositiveValue {
            get {
                return ResourceManager.GetString("PositiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} tem o valor {1} e é maior que o estoque atual do suplemento &apos;{3}&apos;..
        /// </summary>
        public static string QuantityOverStock {
            get {
                return ResourceManager.GetString("QuantityOverStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior que o horário atual.
        /// </summary>
        public static string TimeGreatherThanCurrent {
            get {
                return ResourceManager.GetString("TimeGreatherThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma hora menor ou igual a atual.
        /// </summary>
        public static string TimePresentPast {
            get {
                return ResourceManager.GetString("TimePresentPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um registro com este(a) {0}..
        /// </summary>
        public static string UniqueField {
            get {
                return ResourceManager.GetString("UniqueField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade não encontrada.
        /// </summary>
        public static string UnitNotFound {
            get {
                return ResourceManager.GetString("UnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário com o id {0} não foi encontrado..
        /// </summary>
        public static string UserConnectionNotFound {
            get {
                return ResourceManager.GetString("UserConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um usuário em este e-mail.
        /// </summary>
        public static string UserEmailExists {
            get {
                return ResourceManager.GetString("UserEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é permitido remover a si mesmo.
        /// </summary>
        public static string UserLoggedIdEquals {
            get {
                return ResourceManager.GetString("UserLoggedIdEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O id do usuário logado é obrigatório.
        /// </summary>
        public static string UserLoggedIdRequired {
            get {
                return ResourceManager.GetString("UserLoggedIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um usuário com este nome.
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O repositório de usuários não está disponível..
        /// </summary>
        public static string UsersRepositoryNotAvailable {
            get {
                return ResourceManager.GetString("UsersRepositoryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um usuário com este nome de usuário.
        /// </summary>
        public static string UserUsernameExists {
            get {
                return ResourceManager.GetString("UserUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um e-mail válido.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
    }
}
